<?php

declare(strict_types=1);

namespace Stumason\Coolify\Nixpacks;

use Illuminate\Support\Facades\File;
use Stumason\Coolify\Nixpacks\Detectors\HorizonDetector;
use Stumason\Coolify\Nixpacks\Detectors\PackageDetector;
use Stumason\Coolify\Nixpacks\Detectors\ReverbDetector;
use Stumason\Coolify\Nixpacks\Detectors\SchedulerDetector;

class NixpacksGenerator
{
    /** @var array<PackageDetector> */
    protected array $detectors = [];

    /** @var array<PackageDetector> */
    protected array $detected = [];

    /** @var bool Whether detection has been run */
    protected bool $hasDetected = false;

    /** @var bool|null Cached result of hasNodeDependencies */
    protected ?bool $hasNode = null;

    public function __construct()
    {
        $this->detectors = [
            new HorizonDetector,
            new ReverbDetector,
            new SchedulerDetector,
        ];
    }

    /**
     * Run detection and return list of detected packages.
     * Results are cached - subsequent calls return cached results.
     *
     * @return array<PackageDetector>
     */
    public function detect(): array
    {
        if ($this->hasDetected) {
            return $this->detected;
        }

        $this->detected = [];

        foreach ($this->detectors as $detector) {
            if ($detector->isInstalled()) {
                $this->detected[] = $detector;
            }
        }

        $this->hasDetected = true;

        return $this->detected;
    }

    /**
     * Get the detected packages (must call detect() first).
     *
     * @return array<PackageDetector>
     */
    public function getDetected(): array
    {
        return $this->detected;
    }

    /**
     * Generate the nixpacks.toml content.
     */
    public function generate(): string
    {
        $lines = [];

        // Header
        $lines[] = '# Generated by laravel-coolify';
        $lines[] = '# https://github.com/stumason/laravel-coolify';
        $lines[] = '';

        // Collect all nix packages needed
        $nixPackages = $this->collectNixPackages();
        if (! empty($nixPackages)) {
            $lines[] = '[phases.setup]';
            $lines[] = 'nixPkgs = ['.implode(', ', array_map(fn ($p) => "\"{$p}\"", $nixPackages)).']';
            $lines[] = '';
        }

        // Build phase
        $lines[] = '[phases.build]';
        $lines[] = 'cmds = [';
        $lines[] = '    "composer install --no-dev --optimize-autoloader",';

        // Check for frontend build
        if ($this->hasNodeDependencies()) {
            $lines[] = '    "npm ci",';
            $lines[] = '    "npm run build",';
        }

        // Laravel optimizations
        $lines[] = '    "php artisan config:cache",';
        $lines[] = '    "php artisan route:cache",';
        $lines[] = '    "php artisan view:cache",';

        // Additional build commands from detectors
        foreach ($this->detected as $detector) {
            foreach ($detector->getBuildCommands() as $cmd) {
                $lines[] = "    \"{$cmd}\",";
            }
        }

        $lines[] = ']';
        $lines[] = '';

        // Start command
        $lines[] = '[start]';
        $lines[] = 'cmd = "'.$this->getWebCommand().'"';
        $lines[] = '';

        // Processes
        $processes = $this->collectProcesses();
        if (! empty($processes)) {
            $lines[] = '[processes]';
            $lines[] = 'web = "'.$this->getWebCommand().'"';

            foreach ($processes as $name => $command) {
                $lines[] = "{$name} = \"{$command}\"";
            }

            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * Write the nixpacks.toml file.
     *
     * @throws \InvalidArgumentException If the directory does not exist or path is outside base_path
     */
    public function write(?string $path = null): string
    {
        $path = $path ?? base_path('nixpacks.toml');

        // Resolve to real path for comparison (handles ../ etc)
        $realPath = realpath(dirname($path));
        $basePath = base_path();

        // Validate path is within project directory (security check)
        // realpath returns false if directory doesn't exist, so this also validates existence
        if ($realPath === false || ! str_starts_with($realPath, $basePath)) {
            throw new \InvalidArgumentException(
                'Path must be within the project directory'
            );
        }

        $content = $this->generate();

        File::put($path, $content);

        return $path;
    }

    /**
     * Check if nixpacks.toml already exists.
     */
    public function exists(): bool
    {
        return File::exists(base_path('nixpacks.toml'));
    }

    /**
     * Get the web server command.
     * Configurable via config('coolify.nixpacks.web_command') for Octane support.
     */
    protected function getWebCommand(): string
    {
        return config('coolify.nixpacks.web_command', 'php-fpm');
    }

    /**
     * Collect all nix packages from detectors.
     *
     * @return array<string>
     */
    protected function collectNixPackages(): array
    {
        $packages = [];

        foreach ($this->detected as $detector) {
            $packages = array_merge($packages, $detector->getNixPackages());
        }

        // Add Node.js if needed (version configurable via config)
        if ($this->hasNodeDependencies()) {
            $packages[] = config('coolify.nixpacks.node_version', 'nodejs_20');
        }

        return array_unique($packages);
    }

    /**
     * Collect all processes from detectors.
     *
     * @return array<string, string>
     */
    protected function collectProcesses(): array
    {
        $processes = [];

        foreach ($this->detected as $detector) {
            $processes = array_merge($processes, $detector->getProcesses());
        }

        return $processes;
    }

    /**
     * Check if the project has Node.js dependencies.
     * Result is cached to avoid repeated file system checks.
     */
    protected function hasNodeDependencies(): bool
    {
        if ($this->hasNode === null) {
            $this->hasNode = File::exists(base_path('package.json'));
        }

        return $this->hasNode;
    }

    /**
     * Get a summary of what will be generated.
     *
     * @return array{packages: array<string>, processes: array<string, string>, nix_packages: array<string>}
     */
    public function getSummary(): array
    {
        return [
            'packages' => array_map(fn ($d) => $d->name(), $this->detected),
            'processes' => array_merge(
                ['web' => $this->getWebCommand()],
                $this->collectProcesses()
            ),
            'nix_packages' => $this->collectNixPackages(),
        ];
    }
}
