<?php

declare(strict_types=1);

use Illuminate\Support\Facades\File;
use Stumason\Coolify\Nixpacks\Detectors\HorizonDetector;
use Stumason\Coolify\Nixpacks\Detectors\ReverbDetector;
use Stumason\Coolify\Nixpacks\Detectors\SchedulerDetector;
use Stumason\Coolify\Nixpacks\NixpacksGenerator;

beforeEach(function () {
    // Clean up any existing nixpacks.toml
    $path = base_path('nixpacks.toml');
    if (File::exists($path)) {
        File::delete($path);
    }
});

afterEach(function () {
    // Clean up after tests
    $path = base_path('nixpacks.toml');
    if (File::exists($path)) {
        File::delete($path);
    }
});

describe('NixpacksGenerator', function () {
    it('detects installed packages', function () {
        $generator = new NixpacksGenerator;
        $detected = $generator->detect();

        // In test environment, none of these packages should be installed
        expect($detected)->toBeArray();
    });

    it('generates valid toml content', function () {
        $generator = new NixpacksGenerator;
        $generator->detect();

        $content = $generator->generate();

        expect($content)->toContain('# Generated by laravel-coolify');
        expect($content)->toContain('[phases.build]');
        expect($content)->toContain('[start]');
        expect($content)->toContain('composer install --no-dev --optimize-autoloader');
        expect($content)->toContain('php artisan config:cache');
        expect($content)->toContain('php artisan route:cache');
        expect($content)->toContain('php artisan view:cache');
    });

    it('writes nixpacks.toml file', function () {
        $generator = new NixpacksGenerator;
        $generator->detect();

        $path = $generator->write();

        expect(File::exists($path))->toBeTrue();
        expect(File::get($path))->toContain('[phases.build]');
    });

    it('detects when nixpacks.toml exists', function () {
        $generator = new NixpacksGenerator;

        expect($generator->exists())->toBeFalse();

        File::put(base_path('nixpacks.toml'), '# test');

        expect($generator->exists())->toBeTrue();
    });

    it('includes node build commands when package.json exists', function () {
        // Create a temporary package.json
        File::put(base_path('package.json'), '{}');

        $generator = new NixpacksGenerator;
        $generator->detect();

        $content = $generator->generate();

        expect($content)->toContain('npm ci');
        expect($content)->toContain('npm run build');

        // Clean up
        File::delete(base_path('package.json'));
    });

    it('returns summary of generated config', function () {
        $generator = new NixpacksGenerator;
        $generator->detect();

        $summary = $generator->getSummary();

        expect($summary)->toHaveKeys(['packages', 'processes', 'nix_packages']);
        expect($summary['processes'])->toHaveKey('web');
        expect($summary['processes']['web'])->toBe('php-fpm');
    });

    it('uses php-fpm as default web command', function () {
        $generator = new NixpacksGenerator;
        $generator->detect();

        $content = $generator->generate();

        expect($content)->toContain('cmd = "php-fpm"');
    });
});

describe('HorizonDetector', function () {
    it('returns correct name', function () {
        $detector = new HorizonDetector;

        expect($detector->name())->toBe('Laravel Horizon');
    });

    it('returns horizon process', function () {
        $detector = new HorizonDetector;

        expect($detector->getProcesses())->toBe([
            'horizon' => 'php artisan horizon',
        ]);
    });

    it('requires redis nix package with dynamic php version', function () {
        $detector = new HorizonDetector;
        $phpVersion = PHP_MAJOR_VERSION.PHP_MINOR_VERSION;

        expect($detector->getNixPackages())->toContain("php{$phpVersion}Extensions.redis");
    });
});

describe('ReverbDetector', function () {
    it('returns correct name', function () {
        $detector = new ReverbDetector;

        expect($detector->name())->toBe('Laravel Reverb');
    });

    it('returns reverb process with correct host and port', function () {
        $detector = new ReverbDetector;

        expect($detector->getProcesses())->toBe([
            'reverb' => 'php artisan reverb:start --host=0.0.0.0 --port=8080',
        ]);
    });
});

describe('SchedulerDetector', function () {
    it('returns correct name', function () {
        $detector = new SchedulerDetector;

        expect($detector->name())->toBe('Task Scheduler');
    });

    it('returns scheduler process', function () {
        $detector = new SchedulerDetector;

        expect($detector->getProcesses())->toBe([
            'scheduler' => 'php artisan schedule:work',
        ]);
    });
});
